name: ts-action
description: Project Template of Action which is written by TypeScript

inputs:
  name:
    description: example input
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'